### ISSUE TITLE
personalize / add more info to push-notifications (e.g. "Username" invited you to connect / Your slot invitation for call "@ 1p" has been accepted)

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#394]
For most of the pushes right now to understand the context you have to open the push. Let's make it more convenient for users.

@orlovvlad95 please study this library - https://hexdocs.pm/gettext/Gettext.html. The key command is `mix gettext.extract --merge`.

**Comment by orlovvlad95** [comment]
+ delete messages like "New like.." from tg bot
