### ISSUE TITLE
start recording data for future algorithmic feed 

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#397]
want to build something similar to what TikTok has: basing feed not on their likes, but what users are spending time on:

> TikTok only needs one important piece of information to figure out what you want: the amount of time you linger over a piece of content. Every second you hesitate or rewatch, the app is tracking you
https://www.wsj.com/articles/tiktok-algorithm-video-investigation-11626877477

> Reporters found that watch time — not likes or shares — is the most important piece of information that TikTok collects.

this may also allow to get rid of need for filters (age, location, gender, etc.) at some point

So I am thinking of starting with recording time spent on profile (visible, in foreground) from iOS which will be a payload in `like` and `seen` commands.

@ruslandoga any thoughts on how to best organise the storage on backend / db side?

**Comment by ruslandoga** [comment]
@akhrail1996 I see two ways, one is more efficient but hard, the other is not efficient but easy.

The latter one is sending events for every discreet event similar to

```json
{"event": "viewed", "meta": {"profile": "<uuid>", "started_at": "<timestamp>", "ended_at": "<timestamp>"}, "actor": "<uuid>"}
```

or indeed that info can be added to `seen`.

The former would be similar to tinder approach from https://www.youtube.com/watch?v=j2rfLFYYdfM

**Comment by akhrail1996** [comment]
thanks a lot, liked your way of thinking and ideas :)

So technically in easier case: a separate "event" command handler in `feedChannel` which will record the event into a new write-only `feed_events` table,  probably having following columns:
* user_id
* on_user_id (?)
* event (text?)
* timestamp (probably accuracy to milliseconds?))

Sounds ok?

**Comment by ruslandoga** [comment]
I'd probably use the existing `seen` event in feed channel and store events themselves as jsonb blobs like we did with meta for getsince.app visits / phones. It's a bit hard right now to know what columns the table would need.

**Comment by ruslandoga** [comment]
@akhrail1996 I can start on this with a "low-tech" solution of writing __everything__ to sqlite and uploading it at 03:00 to s3 every night. Inspo: https://news.ycombinator.com/item?id=26581807.

Reasoning:

- s3 + sqlite combo is fast and cheap (~$3/month) 
- sqlite dbs can be imported into clickhouse

**Comment by akhrail1996** [comment]
@ruslandoga sounds great 👍
