### ISSUE TITLE
add match "activating" push 24 hours before match expiration

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#414]
@orlovvlad95 I am mostly focused on increasing the # of calls per active users at the moment.

I think it makes sense to add an additional "match expiration" push 24 hours prior to match expiration with something like "Your match will expire in 24 hours, invite him on an audio-date to keep the music going". Since 1 push just 1 hour prior to match expiration may not be enough in my opinion. What do you think?

You can ask Lily to create an exact text for EN & RU locale keeping in mind the character limit (for push text to be fully visible on all screens).

**Comment by ruslandoga** [comment]
@akhrail1996 still relevant?
