### ISSUE TITLE
next iteration of Since LIVE

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#435]
- [x] enable filters for Since LIVE #450 
- [x] return next Since Live slot time
- [x] fix major bugs in Sentry
- [x] users to be matched after successful call https://github.com/getsince/test3/pull/469
- [x] "user is on another call" error https://github.com/getsince/test3/pull/470

**Comment by ruslandoga** [comment]
@akhrail1996 seems like it's done

**Comment by akhrail1996** [comment]
@ruslandoga right, thanks for noticing!
