### ISSUE TITLE
render "Do Not Disturb" mode CallKit.IncomingCall.Error

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#436]
https://sentry.io/organizations/since-kindly/issues/2719282209/?project=5972007&query=is%3Aunresolved

should probably hang up on the call / optionally rendering "user has do not disturb mode" call end status for the caller

reference:
https://developer.apple.com/documentation/callkit/cxerrorcodeincomingcallerror/2335371-filteredbydonotdisturb
https://stackoverflow.com/questions/49982402/callkit-is-not-showing-incoming-ui-when-device-is-locked

**Comment by ruslandoga** [comment]
@akhrail1996 we won't be to do this on backend alone. iOS needs to send `hang-up` or similar with a custom reason like `error.localizedDescription` to backend which can relay it back to the caller.
