### ISSUE TITLE
PushNotifications.APNSJob failed with {:error, %Mint.HTTPError{module: Mint.HTTP2, reason: {:exceeds_window_size, :connection, 50}}})

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#443]
https://sentry.io/organizations/since-kindly/issues/2868960111/?environment=prod&project=5972006&referrer=alert_email

![image](https://user-images.githubusercontent.com/16062322/146785543-c8b34d37-e2e4-4ffa-a99c-f1a4f810c4b7.png)

**Comment by ruslandoga** [comment]
Some relevant links:

- what's a window size? https://developers.google.com/web/fundamentals/performance/http2/#flow_control
- error description: https://hexdocs.pm/mint/Mint.HTTP2.html#t:error_reason/0

**Comment by ruslandoga** [comment]
@akhrail1996 it should be fixed after finch 0.10.1 release
