### ISSUE TITLE
embrace contact exchange as a gateway drug to audio-dates

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#444]
mirroring https://github.com/getsince/test5/issues/190
- [x] enable storage / updating / rendering of multiple contacts
- [x] add "we_met" match_event
- [x] archived_matches table; archive match command; do not return "archived_matches" on normal mode feedChannel join, only on-demand (separate command?)
- [x] maybe_unarchive_match on slot / contact offer
- [x] add, store and render setting (return with matches) for only accepting audio-date as a first encounter
- [x] switch match expiration from rolling 48 hours to fixed 7 days
- [x] force upgrade to 4.8.0
- [x] check for support of 7 day in future timeslot offer
- [ ] guarantee expired matchers to not see each others for seen prune period
- [x] add tests

**Comment by ruslandoga** [comment]
@akhrail1996 is this still a WIP or is it done already and can be closed?

**Comment by akhrail1996** [comment]
@ruslandoga yup, only one left: https://github.com/getsince/test3/issues/552
