### ISSUE TITLE
add voicemail

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#474]
related to https://github.com/getsince/test5/issues/197

what needs to be done:
- [x] maybe create a special bucket for voicemail storage;
- [x] add `send-voicemail` command to feed_channel (ref: https://github.com/getsince/test5/pull/196/files#diff-ff2ea48ff2f5f39ca8c03130d73e2dcb1e534ad449e4020fa77ec29657958c17R338)
- [x] ~~add `cancel-voicemail` command to feed_channel (ref: https://github.com/getsince/test5/pull/196/files#diff-ff2ea48ff2f5f39ca8c03130d73e2dcb1e534ad449e4020fa77ec29657958c17R350)~~
- [x] make match action (send voicemail / contact / timeslot offer) cancel the previous mode. I.e. A sends B (his match) voicemail -> B listens to voicemail and sends timeslot offer / contact -> A's voicemail should be removed since now this match is in "timeslot offer / contact exchange" mode. Same thing if A sends B a contact -> B sends voicemail to A  (this goes out of the scope of this issue a bit)
- [x] record voicemail - maybe `match_voicemail` table?
- [x] render voicemail for relevant matches
- [x] ~~reset match_expiration_period from 7 days to 48 hours~~
- [x] return match_expiration_period back to 7 days ❤️‍🩹
- [x] ~~change match expiration timer logic - now timer expires if users either had  a successful audio call (same as now) or exchanged voicemail (at least 1 voice message from both sides; different from now). "we met report" can be kept to support current users (so that their matches wouldn't suddenly expire) + it will now be impossible to report "that you met" prior to match expiration timer reset~~
- [x] add new voicemail_expiration_period and set it to 48 hours
- [x] voicemail_expiration timer expires if users exchanged voicemail (at least 1 voice message from both sides)
- [x] related to https://github.com/getsince/test5/issues/197

P.S. above most likely requires some additions / changes / reconsideration

**Comment by akhrail1996** [comment]
@ruslandoga I would appreciate if you could start with adding audio support to `upload-preflight` here:  https://github.com/getsince/test3/blob/master/lib/t_web/channels/profile_channel.ex#L26

frontend ref:
https://github.com/getsince/test5/pull/196/files#diff-6b2ce5ac5809c6ef8c85e0a6a1fd20bee38f23d1bef4e6882c1562445fbb517aR23
https://github.com/getsince/test5/blob/rails-fork/Since/Networking/Media.swift#L97

**Comment by ruslandoga** [comment]
@akhrail1996 do you really need audio uploads on profile channel?

**Comment by akhrail1996** [comment]
my bad, then here: https://github.com/getsince/test3/blob/master/lib/t_web/controllers/media_controller.ex

**Comment by ruslandoga** [comment]
@akhrail1996 https://github.com/getsince/test3/pull/477

**Comment by ruslandoga** [comment]
@akhrail1996 ios also needs to send `delete-voicemail` with id or `clear-voicemail` to delete all listened to messages.

**Comment by ruslandoga** [comment]
@akhrail1996 does `cancel-voicemail` have a timer or something like that?

**Comment by ruslandoga** [comment]
Also note that voicemail won't be encrypted by default, so the app permission requests might need to be updated.

**Comment by akhrail1996** [comment]
> Also note that voicemail won't be encrypted by default, so the app permission requests might need to be updated.

could you please clarify? do you mean some additional permission to Info.plist?

> And since the bucket is public-read, anyone can listen anyone else's voicemail provided they have the s3 key.

will it be hard to switch to a private-read model later?

> @akhrail1996 does `save-voicemail` sets a timer that `cancel-voicemail` cancels? Or does it rely only on the happy path, that the receiver hasn't downloaded the message yet?

actually, as I think more about it - we don't need this `cancel-voicemail` thing at all.

> @akhrail1996 ios also needs to send `delete-voicemail` with id or `clear-voicemail` to delete all listened to messages.

probably not needed as well, I will edit the issue body now

**Comment by ruslandoga** [comment]
> could you please clarify? do you mean some additional permission to Info.plist?

The app used to save voice communication is encrypted when requesting microphone permissions.

> probably not needed as well, I will edit the issue body now

> will it be hard to switch to a private-read model later?

It mostly depends on the client, on backend it's a one line change. Signed-urls are already supported.

> probably not needed as well, I will edit the issue body now

I think we need to delete messages that have been listened to from backend, both for privacy and cost reasons.

**Comment by akhrail1996** [comment]
> The app used to say voice communication is encrypted when requesting microphone permissions.

Yeah, not anymore: "This will allow you to communicate with new people on audio-dates.".
But yeah, should be updated anyways, good catch 👍

> It mostly depends on the client, on backend it's a one line change. Signed-urls are already supported.

Is it hard on client then?

> I think we need to delete messages that have been listened to from backend, both for privacy and cost reasons.

yeah, but the way they will work (at least in current version) doesn't require explicit "delete-voicemail" command from client - can be done behind the scenes on backend:
* either when match expires;
* when user B listened to A voicemail and recorded a reply -> A's voicemail can be deleted 
* when match "interaction mode" change (user A sent voicemail -> B listened to it and decided to send his contact -> match "interaction mode" (what gets rendered with match) changes from `voicemail` to `contact` exchange -> voicemail can safely be deleted).

**Comment by ruslandoga** [comment]
so matches become a state machine, that's nice

**Comment by akhrail1996** [comment]
> So matches become a state machine, maybe we could store the current interaction mode in matches table?

yeah seems like a natural evolution

**Comment by ruslandoga** [comment]
- [ ] delete voicemail on unmatch or anything that causes match to be deleted

**Comment by ruslandoga** [comment]
@akhrail1996 what's `voicemail_exchange_expiration` timer exactly?

**Comment by akhrail1996** [comment]
> @akhrail1996 what does `voicemail_exchange_expiration` timer do when it fires?

it "expires" the match, the same way as `match_expiration` timer expires it now

In simple words now users have 48 hours to exchange voicemail and 7 days to have a call / exchange contacts to not expire

**Comment by ruslandoga** [comment]
@akhrail1996 is this correct:

- if users have exchanged voicemail within 48 hours and haven't had a call within 7 days, match expires
- if users have had a call within 48 hours, but haven't exchanged voicemail, *the match doesn't expire*
- if users have not exchanged voicemail and haven't had a call within 48 hours, the match expires
- if users have if users have exchanged voicemail within 48 hours and then had a call within 7 days, the match doesn't expire

**Comment by akhrail1996** [comment]
> @akhrail1996 is this correct:
> 
> * if users have exchanged voicemail within 48 hours and haven't had a call within 7 days, match expires

call / "we met report" - yes

> * if users have had a call within 48 hours, but haven't exchanged voicemail, **the match doesn't expire**

voicemail exchange is the first obligatory action (call won't be available prior to this)

> * if users have not exchanged voicemail and haven't had a call within 48 hours, the match expires

if users have not exchanged voicemail, the match expires

> * if users have if users have exchanged voicemail within 48 hours and then had a call within 7 days, the match doesn't expire

had a call / "we met report" - yes
