### ISSUE TITLE
make "invite" in LIVE mode into "voice message as invite"

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#505]
last LIVE stats:

![image](https://user-images.githubusercontent.com/16062322/148761136-d665a0b1-0184-42bb-8e64-4b63d770cc61.png)

ratio of calls to invites is super low. I think adding voice message invite may help here (nothing much to lose anyways)

**Comment by ruslandoga** [comment]
blocked by https://github.com/getsince/test3/issues/550

**Comment by ruslandoga** [comment]
closing due to #550
