### ISSUE TITLE
 drop "meeting reported" as a timer expiration event with "contact send" filling its role instead

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#541]

**Comment by akhrail1996** [comment]
"contact opened" is probably too hard to grasp - simple "contact send" will do

**Comment by akhrail1996** [comment]
@ruslandoga okay if I do this one?

**Comment by ruslandoga** [comment]
@akhrail1996 yes, but outline the approach first, please.

**Comment by akhrail1996** [comment]
@ruslandoga pretty simple:
* add `match_event` of type `contact_shared` in `save_contact` Multi
* add `contact_shared` to `undying_event_types`

this will probably minimize breaking changes, later we can drop "meeting_reports" altogether (from feed_channel's handle_in & as undying event (inserting 'contact_shared' into match_event history instead) & from everywhere)

**Comment by ruslandoga** [comment]
- add migration to insert `contact_shared` event for each `meeting_reported`

**Comment by ruslandoga** [comment]
- `later we can drop "meeting_reports" altogether (from feed_channel's handle_in` needs an issue
