### ISSUE TITLE
disable real "LIVE" mode

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#545]
2 reasons:
- people are not using it much
- we don't have design (both product-wise & visual) for it yet (as part of chat redesign)

**Comment by ruslandoga** [comment]
@akhrail1996 can live be removed?

**Comment by akhrail1996** [comment]
@ruslandoga I still want to come up with the right approach to LIVE, but not sure when this will happen
so probably just disabling it the optimal for now

**Comment by ruslandoga** [comment]
what should be done about the issues above?

**Comment by akhrail1996** [comment]
all closed?

**Comment by ruslandoga** [comment]
> Then https://github.com/getsince/test3/issues/467, https://github.com/getsince/test3/issues/505, and https://github.com/getsince/test3/issues/461 could be closed.

**Comment by akhrail1996** [comment]
@ruslandoga, yes I am referring to them

**Comment by ruslandoga** [comment]
So you want to just close them?

**Comment by akhrail1996** [comment]
@ruslandoga okay then maybe it makes sense to say a deadline (say next weekend):
- if there will be some more material ideas (of how LIVE can work) + understanding of timing by then => keep alive
- no ideas => remove

sounds good?

**Comment by akhrail1996** [comment]
@ruslandoga LIVE can be removed after all 😉
