### ISSUE TITLE
do not return expiredMatches on feedChannel.join

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#587]
now (given that) we only have contacts in profile it's actually counter-logical to return expiredMatches (since the receiver would still see their private contacts)

**Comment by ruslandoga** [comment]
this would be a breaking chnage

**Comment by akhrail1996** [comment]
> this would be a breaking change

not really, since it's optional on frontend
https://github.com/getsince/test5/blob/add-seen-id-to-chat-version/Since/Feeds/Normal%20Feed/NormalFeedChannel.swift#L42

it would kinda alter the previous user flow, but not very much

alternatively it can be done in "remove-interactions" breaking change PR: https://github.com/getsince/test3/pull/560/files#diff-a0218a402f6110a957246806c0683922fda46cc95037890c7aae13528effb6a0L58

**Comment by ruslandoga** [comment]
`remove interactions` would be merged once there are no client left on `5.*` version

**Comment by akhrail1996** [comment]
then expired_matches shouldn't be returned in `remove-interactions` PR here:
https://github.com/getsince/test3/pull/560/files#diff-a0218a402f6110a957246806c0683922fda46cc95037890c7aae13528effb6a0L58

plus the corresponding functionality (storing to "expired_matches" table, "seen" expired_match, etc.)

**Comment by ruslandoga** [comment]
seems to be done
