### ISSUE TITLE
reset match expiration timer after "contact-click" event

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#588]

**Comment by ruslandoga** [comment]
there's already `open-contact` for that

**Comment by ruslandoga** [comment]
@akhrail1996 I assume the timer should be deleted, not reset? I click a contact -> no more timer. Or should it be I click a contact -> timer is 7 days again.

**Comment by akhrail1996** [comment]
> @akhrail1996 I assume the timer should be deleted, not reset? I click a contact -> no more timer. 

correct
