### ISSUE TITLE
maybe move existing contact labels & even ever shared contacts (?) to private pages (?)

### ISSUE THREAD

**Issue by akhrail1996** [getsince/test3#602]

**Comment by akhrail1996** [comment]
@ruslandoga 
this can be used as a "placeholder" blurred page background for profiles with only email:

url: https://since-when-are-you-happy.s3.amazonaws.com/48f74064-ddc3-4072-89d7-cf0da9415d4e
s3key: 48f74064-ddc3-4072-89d7-cf0da9415d4e

**Comment by ruslandoga** [comment]
@akhrail1996 this seems to be done
